name: xuprememax
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  dio: ^5.7.0
  downloadsfolder: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^14.3.0
  path_provider: ^2.1.4
  signals: ^6.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
    - .env

spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  package: resources
  groups:
    - path: assets/images
      class_name: AppImages
      types: [.png]
    - path: assets/svg
      class_name: AppSvg
      types: [.svg]
